import type { Metadata } from "next";
import { Cabin } from "next/font/google";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Initialize Cabin font
const cabin = Cabin({
  variable: "--font-cabin",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${cabin.variable}`}>{children}</body>
    </html>
  );
}
